name: portfolio
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.0.0
  provider: ^6.0.5
  svg_flutter: ^0.0.1
  # flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/hero_bg.jpeg
  
  fonts:
    - family: Syne
      fonts:
        - asset: assets/font/Syne-Bold.ttf
        - asset: assets/font/Syne-Medium.ttf
        - asset: assets/font/Syne-Regular.ttf
        - asset: assets/font/Syne-SemiBold.ttf