name: portfolio
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bot_toast: ^4.1.3
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_screenutil:
  go_router: 
  google_fonts: 
  provider: 
  url_launcher: 
  # svg_flutter: ^0.0.1
  # video_player: ^2.8.2
  # flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 

flutter:
  uses-material-design: true
  assets:
    - assets/
    # - assets/svg/
    - assets/png/
    - assets/video/
  
  fonts:
    - family: Syne
      fonts:
        - asset: assets/font/Syne-Bold.ttf
        - asset: assets/font/Syne-Medium.ttf
        - asset: assets/font/Syne-Regular.ttf
        - asset: assets/font/Syne-SemiBold.ttf